import Head from 'next/head'
import Link from 'next/link';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] });
const data = require('../../data/data.json');

export default function Home() {
  console.log(data);
  return (
    <>
      <Head>
        <title>Learn! Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <h1 className="title">
  Read <Link href="/product">this page!</Link>
</h1>
      </main>
    </>
  )
}
